version: "3.9"
services:
  vault-agent:
    image: vault:1.7.0
    restart: always
    command: [
      'vault',
      'agent',
      '-config=/vault/ProjectAcme/vault-agent/config-vault-agent-template.hcl'
    ]
    volumes:
      - ./ProjectAcme:/vault/ProjectAcme:rw
    cap_add:
      - IPC_LOCK
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
networks:
  vpcbr:
    external:
      name: vault-mssql_vpcbr
