version: "3.9"
services:
  vault:
    image: library/vault:1.7.0
    container_name: vault
    hostname: vault
    ports:
      - "127.0.0.1:8200:8200"
    volumes:
      - ${PWD}/vault/file:/vault/file:rw
      - ${PWD}/vault/config:/vault/config:rw
      - ${PWD}/vault/administrative-policies.hcl:/administrative-policies.hcl:rw
      - ${PWD}/vault/readonly-policies.hcl:/readonly-policies.hcl:rw
      - ${PWD}/vault/readonly.sql:/readonly.sql:rw
    environment:
      - EXAMPLE=example
    # This is required in order for Vault to lock memory,
    # which prevents it from being swapped to disk.
    cap_add:
      - IPC_LOCK
    entrypoint: >
      vault server
      -config=/vault/config/vault.hcl
  # vault-agent:
  #   image: library/vault:1.7.0
  #   container_name: vault-agent
  #   hostname: vault-agent
  #   restart: always
  #   command: [
  #     'vault',
  #     'agent',
  #     '-config=/opt/vault-agent/config-vault-agent-template.hcl'
  #   ]
  #   volumes:
  #     - ${PWD}/vault-agent:/opt/vault-agent:rw
  #   cap_add:
  #     - IPC_LOCK
  sqlserver:
    build:
      context: ${PWD}/sqlserver
      dockerfile: Dockerfile
    container_name: sqlserver
    hostname: sqlserver
    restart: always
    env_file:
      - sqlserver.env
    environment:
      ACCEPT_EULA: 'Yes'
      SA_PASSWORD: "${SQL_SERVER_USER_PASSWORD}"
      MSSQL_PID: 'Developer'
    ports:
      - "127.0.0.1:1433:1433"
    volumes:
      - ${PWD}/sqlserver/InsertRandomData.sql:/InsertRandomData.sql:rw
  adminer:
    image: library/adminer:4.8.0
    container_name: adminer
    hostname: adminer
    restart: always
    ports:
      - 8080:8080
  # app:
  #   container_name: app
  #   build: ./app
  #   links:
  #     - vault:vault
  #     - sqlserver:sqlserver
  #   environment:
  #     ROLE_ID: test
  #     SECRET_ID: 9b10b201-8aaa-dfb8-6dda-e7d9af1f3d19
  #     VAULT_URL: http://vault:8200
  #     SQL_SERVER_ADDR: sqlserver
